- name: Declare variable at Play level
  hosts: all
  connection: local
  vars:
    url: play.example.com
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: url == {{url}}

- name: Declare variable in another file
  hosts: all
  connection: local
  vars_files:
   - var.yml
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: url == {{url}}
## vars can also be declared on the task level

- name: Declare variable at task level
  hosts: all
  connection: local
  tasks:
    - name: Declare and access a variable
      ansible.builtin.debug:
        msg: url == {{url}}
      vars:
        url: task.example.com

- name: Declare variable from inventory file
  hosts: all
  connection: local
  tasks:
    - name: Declare and access a variable
      ansible.builtin.debug:
        msg: url == {{url}}

- name: Access of Facts
  hosts: all
  connection: local
  tasks:
    - name: Access fact
      ansible.builtin.debug:
        msg: Ansible Host name == {{ansible_fqdn}}

- name: Register a variable
  hosts: all
  connection: local
  tasks:
    - name: run a shell command
      ansible.builtin.shell: uptime
      register: out
    - name: Print out
      ansible.builtin.debug:
        msg: "{{out.stdout}}"
    - name: set a fact
      ansible.builtin.set_fact:
        OUTPUT: "{{out.stdout}}"